BEGIN TRANSACTION;

	CREATE TABLE IF NOT EXISTS Producto(
		CVE_Producto INTEGER PRIMARY KEY AUTOINCREMENT,
		Descripcion VARCHAR(20) NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS Medidas(
		CVE_Medidas INTEGER PRIMARY KEY AUTOINCREMENT,
		Alto INT NOT NULL CHECK(Alto > 0),
		Ancho INT NOT NULL CHECK(Ancho > 0)
	);

	CREATE TABLE IF NOT EXISTS MedidasProducto(
		CVE_MedidasProducto INTEGER PRIMARY KEY AUTOINCREMENT,
		Precio INT NOT NULL CHECK(Precio > 0),
		CVE_Medidas INT,
		CVE_Producto INT NOT NULL,
		FOREIGN KEY(CVE_Medidas)
			REFERENCES Medidas(CVE_Medidas),
		FOREIGN KEY(CVE_Producto)
			REFERENCES Producto(CVE_Producto)
	);

COMMIT;